Refactors user data queries
acmutsa/HackKit pull request #98
Opened 2024-08-16 04:37 UTC by xwilson03

## Description:
Replaces heavily duplicated user data queries with functions that return new standard user interface types.

Closes #96

### Reviewers:
- Required: ...
- Optional: ...

### Review Guide:
- ...

## Changelog:

### ...
- ...

2024-08-25 02:08 UTC, Lermatroid requested changes, later dismissed

2024-08-25 02:08 UTC, Lermatroid commented on package.json
Any reason we are removing migration execution? This could lead to easy de-syncs between prod and the db state.

2024-08-25 02:08 UTC, Lermatroid commented on packages/db/functions/user.ts
I'm still pretty concerned about the use of prepared statements here. There are 2 main reasons to use prepared statements: 

a) Security: prepared statements can prevent sql injection since you are not doing weird string templating. This does not really apply in a ORM though which in iteself safe guards against sql injection.

b) performance: prepared statements can starry to save some minor work when executing a statement _alot_ of times. This gets negated though due to our serverless environment which will forget this work. Furthermore, this removes the strict types of drizzle and instead manually sets types making these queries go from strongly typed to type annotated. This is quite discouraged when avoidable and changes in drizzles api will not be reflected in our return types which could yield unexpected behavior.

For those reasons I think we should really consider moving to returning the results of standard drizzle queries.

2024-08-25 02:08 UTC, Lermatroid commented on packages/db/functions/index.ts
Maybe instead of exporting all at index we export from each sub folder? That way separate queries areas do not all flow into one namespace.

2024-08-25 02:08 UTC, Lermatroid commented on packages/db/functions/hacker.ts
Similar concerns around prepared statements here

2024-08-31 02:08 UTC, xwilson03 commented on package.json
This is temporary to allow pushes without messing up the prod db; its on the post-review to-do list and will be resolved before merging.

2024-09-06 07:36 UTC, christianhelp commented
For future reference and reviewer sanity, it might be nice to point this PR to the sister PR #77 and then point it back to dev afterwards just so we don't have to go through a lot of the same files bc 58 files is a lot.

2024-09-06 07:45 UTC, christianhelp commented on packages/db/functions/index.ts
I think this might be a good idea to consider. Even though these are exported from a central index file, you can still import them as either `import {...} from 'db/functions'` or you can do `import {...} from 'db/functions/user'`, but that relies on the developer to add that extra piece. My VS code seems to default to `db/functions`.

2024-09-10 18:45 UTC, christianhelp commented on packages/db/functions/index.ts
Talked offline with @xwilson03, we think that this export is fine.

2024-09-10 19:13 UTC, christianhelp submitted a review, later dismissed

2024-09-11 15:09 UTC, christianhelp submitted a review, later dismissed

2024-09-11 15:27 UTC, christianhelp approved these changes

2024-09-11 15:27 UTC, merged