48 times of event do not display correct times
acmutsa/HackKit pull request #99
Opened 2024-08-17 17:30 UTC by christianhelp

## Why
As of now, the time of an event does not reflect correctly due to issues with how the time is converted from the server.

## What
- Add helpers to leverage the use of Vercel headers to get a user's timezone that is sent to the server upon request of a server component
- Added a types folder 
- Updated schedules display in order to properly show the times of an event accurately from any timezone

## Satisifes
HK-122(#48)

## NOTE
There were concerns on the approach to solve this issue as the page that uses the timezone headers will run on the edge. By definition and our knowledge, this should mean that it would not work in a production environment. However, upon doing a bit more research, it seems that these headers were made for the edge network. The developer with concerns has been assigned to approve this PR.

Resources are linked here:
[X-Vercel-ip-timezone](https://vercel.com/docs/edge-network/headers#x-vercel-ip-timezone)
[Vercel Discussion where request seems to stem from ](https://github.com/orgs/vercel/discussions/94)

2024-08-18 00:53 UTC, Lermatroid commented
Ok starting review! Just a heads up though its not that the headers are on the edge or not work in production. It does work in Vercel production and preview environments, but not on non-vercel platforms / edge. TLDR: vendor lock-in for people who do not want to host on vercel 👍

2024-08-18 00:54 UTC, Lermatroid commented
I dont think the linear pairing worked properly

Fixes https://linear.app/acmutsa/issue/HK-122/times-of-event-do-not-display-correct-times

2024-08-18 00:58 UTC, Lermatroid commented
Ok starting review! Just a heads up though its not that the headers are on the edge or not work in production. It does work in Vercel production and preview environments, but not on non-vercel platforms / edge. TLDR: vendor lock-in for people who do not want to host on vercel 👍

2024-08-18 01:05 UTC, Lermatroid commented
Looks great! Times seem to working properly. I think some of the UI could use a a little bit of enhancing but IK that is something we already discussed and is more applicable to a different PR. LGTM ✅

2024-08-18 01:12 UTC, Lermatroid commented on apps/web/src/lib/queries/events.ts
Not blocking, but I think we should consider moving queries to the db package. cc @xwilson03

2024-08-18 01:23 UTC, christianhelp commented on apps/web/src/lib/queries/events.ts
I think you’re right on that. I also think that might make more sense too.

2024-08-18 01:50 UTC, Lermatroid requested changes, later dismissed
Left some feedback. Overall great PR! Very much was something in need of a fix so cheers all around for the research / implementation. 

Comments mostly revolve overall on what imo is over-obscuring of functionality or not obscuring it in what I would argue is a healthy way for the developers first laying eyes on it w/ some explanations of my reasoning & external sources.

2024-08-18 01:50 UTC, Lermatroid commented on apps/web/src/lib/utils/client/shared.ts
This file has alot of functions that either:

a) do not get used
b) only get used once w/o being much more concise that just defining in place
c) or cover over eachother with something that could be a default param

[JS Dates are pretty bad](https://gist.github.com/Lermatroid/8fb1fbaa69367b6b36607cbc40290e7b), and while hopefully [temporal](https://medium.com/@imanmalekian31/how-to-work-with-temporal-date-api-f7bcc9bcce49) fixes these natively in the future, I think it would be good for us to use something like [luxon](https://github.com/moment/luxon/) or [date-fns](https://github.com/date-fns/date-fns?tab=readme-ov-file). 

 I'd argue what this file is doing is more or less trying to build a date library, and I think we would be better off using one that makes sure we don't footgun ourselves, is tree-shakeable, and has had years of thought and care put into how it works / is battletested.

2024-08-18 01:50 UTC, Lermatroid commented on apps/web/src/lib/queries/events.ts
I think we should consider moving queries to the db package. Not blocking tho :)

cc @xwilson03

2024-08-18 01:50 UTC, Lermatroid commented on apps/web/src/lib/constants/shared.ts
This file feels like a not good idea imo. I think there are 2 types of values here:

a) ones that change
b) ones that are truly constant

For point B I think `hackkit.config.ts` and `.env` should always be the point of truth. Spreading them out yields confusion for developers and both of those sources are supported cross-packages.

For A, I think that these things should mostly be defined inline. My take on it is [well explained here](https://stackoverflow.com/questions/27026019/should-single-use-values-be-inline-function-level-const-variables-or-class-lev).

2024-08-18 01:50 UTC, Lermatroid commented on packages/db/schema.ts
Any reason for the commented out stuff here?

2024-08-18 01:53 UTC, christianhelp commented on packages/db/schema.ts
It is going to be in the next iteration and is a placeholder as I work through stuff

2024-08-18 01:57 UTC, Lermatroid commented on apps/web/src/lib/constants/shared.ts
Overall, I think `Right Click > Go To Definition`  tab switching avoidance where there is not a very obvious code clarity benefit is a good thing :)

2024-08-18 01:59 UTC, Lermatroid commented on packages/db/schema.ts
Sounds good 👍

2024-08-18 02:07 UTC, christianhelp commented
> Ok starting review! Just a heads up though its not that the headers are on the edge or not work in production. It does work in Vercel production and preview environments, but not on non-vercel platforms / edge. TLDR: vendor lock-in for people who do not want to host on vercel 👍

I agree and I can think of a better way to handle this later on. However, for now I believe we should stick with this unless there is a better idea.

2024-08-18 02:08 UTC, Lermatroid commented
> > Ok starting review! Just a heads up though its not that the headers are on the edge or not work in production. It does work in Vercel production and preview environments, but not on non-vercel platforms / edge. TLDR: vendor lock-in for people who do not want to host on vercel 👍
> 
> I agree and I can think of a better way to handle this later on. However, for now I believe we should stick with this unless there is a better idea.

100%. Just was adding context to the PR 👍

2024-08-18 02:10 UTC, christianhelp commented on packages/db/schema.ts
I originally wanted to add these in this PR, but figured it would be better to make them a separate PR. I also was afraid I would forget my ideas. Hindsight 20/20, I will just add whatever stuff I wanted to change into that issue description.

2024-08-18 02:41 UTC, christianhelp commented on apps/web/src/lib/constants/shared.ts
I suppose so. I just like the idea of not having every single constant being inside of the config because I thought the whole point of config kind of means things that the values can change and are configurable. All 3 of the constants inside of that file should never be changed imo. I would be open to creating a 'constants' key and adding all the values that will be constant under that. I also think I can make them a bit more general as people may opt to use S3 or any other sort of buckets.

2024-08-18 02:42 UTC, christianhelp commented on apps/web/src/lib/queries/events.ts
Yeah that makes sense. I can make that fix

2024-08-18 02:59 UTC, christianhelp commented on apps/web/src/lib/utils/client/shared.ts
That is fair I was not aware of the issues with JS dates. I can adjust it

2024-08-18 05:53 UTC, christianhelp commented on apps/web/src/lib/constants/shared.ts
After looking into it a bit more, I feel more strongly about my opinion. A constant folder helps us separate our concerns. The constants folder will hold all _immutable_ constants and the config will hold all of our _configurable_ constants. Furthermore, almost every project structure makes the argument of having a constant folder. Will link some sources down below for you to check out. I think one of the big things to note is that a lot of projects possess both a config and constants. They can and absolutely should coexist. As for the right click -> go to definition, most modern IDEs allow you to hover over the values and just see what is declared. Another thing I will throw in there is that these constants are going to grow as we update or add more things to Hackkit. If we are to keep them in the config, that is just going to make it unnecessarily larger and harder to read and understand for new devs. I also believe it would violate a separation of concerns. May I also ask where you saw that a project should not have constants? I cannot seem to find a lot arguing against the use of them. I do not mind chatting offline about this as well if it becomes too long of a discussion.

Sources:
- [Medium Article Discussing Next JS structure ](https://medium.com/@pablo.delvalle.cr/an-opinionated-basic-next-js-files-and-directories-structure-88fefa2aa759)
- [Organizing constants and reasons why we use them](https://semaphoreci.com/blog/constants-layer-javascript)
- [More justification for the use of constants](https://medium.com/@z_callan/javascript-project-architecture-constants-deddfde3c8a8)

Please excuse any typos, but I wanted to get this out before I went to bed so you can check it out whenever

2024-08-18 06:10 UTC, christianhelp commented on apps/web/src/lib/constants/shared.ts
Actually, the bucket url can be changed so I will move that to the config

2024-08-18 06:35 UTC, xwilson03 commented on apps/web/src/lib/queries/events.ts
Hey y'all! Definitely agree with this one. #98 is working on this at the moment, although @christianhelp and I have talked offline about changing the current iteration there to use a folder based approach instead. Should help us in avoiding merge conflicts.

2024-08-18 06:46 UTC, christianhelp commented on apps/web/src/lib/queries/events.ts
Yep! I just updated this PR to match

2024-08-18 06:50 UTC, xwilson03 commented on apps/web/src/lib/constants/shared.ts
> After looking into it a bit more, I feel more strongly about my opinion. A constant folder helps us separate our concerns. The constants folder will hold all _immutable_ constants and the config will hold all of our _configurable_ constants. Furthermore, almost every project structure makes the argument of having a constant folder. Will link some sources down below for you to check out. I think one of the big things to note is that a lot of projects possess both a config and constants. They can and absolutely should coexist. As for the right click -> go to definition, most modern IDEs allow you to hover over the values and just see what is declared. Another thing I will throw in there is that these constants are going to grow as we update or add more things to Hackkit. If we are to keep them in the config, that is just going to make it unnecessarily larger and harder to read and understand for new devs. I also believe it would violate a separation of concerns. May I also ask where you saw that a project should not have constants? I cannot seem to find a lot arguing against the use of them. I do not mind chatting offline about this as well if it becomes too long of a discussion.
> 
> Sources:
> 
> * [Medium Article Discussing Next JS structure ](https://medium.com/@pablo.delvalle.cr/an-opinionated-basic-next-js-files-and-directories-structure-88fefa2aa759)
> * [Organizing constants and reasons why we use them](https://semaphoreci.com/blog/constants-layer-javascript)
> * [More justification for the use of constants](https://medium.com/@z_callan/javascript-project-architecture-constants-deddfde3c8a8)
> 
> Please excuse any typos, but I wanted to get this out before I went to bed so you can check it out whenever

I support having the constants file for absolutely immutable things like HOURS_TO_MILLISECONDS. Bucket URL not so much, but that's already been mentioned as something to fix so otherwise I agree with this as something going forwards.

I am a bit curious about how many constants we would need to reference in many places, but either way the config file is huge enough already so anything that prevents that from bloating further is likely to be a good addition in my book.

2024-08-18 06:56 UTC, xwilson03 commented on apps/web/src/lib/constants/shared.ts
Slight addition to my previous comment; I would wager that future PRs will stumble across some inline constants as I have in my recent refactors (although I forget quite where).

In those cases, moving discovered inline constants to an established spot is something that can be tacked onto an existing PR without much additional reasoning, whereas having to establish a new location for those constants is moreso deserving of its own PR and may be forgotten about if issues are not made to track them.

2024-08-18 06:58 UTC, Lermatroid commented on apps/web/src/lib/constants/shared.ts
So, those arguments are more so about how to organize constants, not whether "global constants" should be a used thing. I am more so arguing that global constants are bad alot of the time, and in my view specifically in a project of our size / stage and what we are using them for. 

Next.js, especially with the advent of app directory where there are reserved filed names instead of using filenames as routing, encourages you to build around features, not a arbitrary structure. Arbitrary structuring sounds good in theory, putting everything into its own section based on type of thing, but in practice moves code far away from each other and less practical to work with code.

Dan abramov, who helps lead the react core team and wrote CRA / Redux, shared the view of the react team on this [here]( https://shottr.cc/s/1on4/SCR-20240817-xi7.png) where everything should be colocated as much as possible.

cal.com is a good example of a large ([us](https://api.github.com/repos/acmutsa/hackkit/languages) vs [them](https://api.github.com/repos/calcom/cal.com/languages)) and healthy codebase (and ties this PR as its used for scheduling). It  _does_ have a shared constants file, but uses it exceedingly sparingly. It also does not use it for anything like what we are beyond headers. In fact it does not store any numbers at all even though they do a lot of time and date operations.

Code colocation is widely considered best practice until it is very obvious as to why you cannot, and I don't think we are at that point with the current state of the constants file. The only one I sort of understand is the header, but at that point we are at one constant which would prob get replaced in the future when we add support for non-vercel hosting platforms with a function of some sort.

end of day though I do not not agree with https://react-file-structure.surge.sh/

2024-08-18 07:01 UTC, Lermatroid commented on apps/web/src/lib/constants/shared.ts
So, those arguments are more so about how to organize constants, not whether "global constants" should be a used thing. I am more so arguing that global constants are bad alot of the time since they go against code colocation, and in my view specifically in a project of our size / stage and what we are using them for. 

Next.js, especially with the advent of app directory where there are reserved filed names instead of using filenames as routing, encourages you to build around features, not a arbitrary structure. Arbitrary structuring sounds good in theory, putting everything into its own section based on type of thing, but in practice moves code far away from each other and less practical to work with code.

Dan abramov, who helps lead the react core team and wrote CRA / Redux, shared the view of the react team on this [here]( https://shottr.cc/s/1on4/SCR-20240817-xi7.png) where everything should be colocated as much as possible.

cal.com is a good example of a large ([us](https://api.github.com/repos/acmutsa/hackkit/languages) vs [them](https://api.github.com/repos/calcom/cal.com/languages)) and healthy codebase (and ties this PR as its used for scheduling). It  _does_ have a shared constants file, but uses it exceedingly sparingly. It also does not use it for anything like what we are beyond headers. In fact it does not store any numbers at all even though they do a lot of time and date operations.

Code colocation is widely considered best practice until it is very obvious as to why you cannot, and I don't think we are at that point with the current state of the constants file. The only one I sort of understand is the header, but at that point we are at one constant which would prob get replaced in the future when we add support for non-vercel hosting platforms with a function of some sort.

end of day though I do not not agree with https://react-file-structure.surge.sh/

2024-09-09 17:44 UTC, christianhelp commented on apps/web/src/lib/constants/shared.ts
Discussed offline. Decided it was non-blocking and good to move for now after changes are made.

2024-09-11 05:02 UTC, merged